name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 13 * * 1,3,5"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SECRET_FOR_METRICS }}
          
          # Options
          user: Robert-xiaoqiang
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          config_animations: no
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_ignored: Roff, Jupyter Notebook
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: verified, automater, infographile, worker, forker, follower, reviewer, scripter, explorer, stargazer, developer
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
